server: 
  port: 9999
spring:
  application:
    name: kube
  jackson:
    serialization:
      write-dates-as-timestamps: false #\u662F\u5426\u65F6\u95F4\u6233\u683C\u5F0F
      indent-output: true  #\u683C\u5F0F\u5316\u8F93\u51FA
    dateFormat: yyyy-MM-dd HH:mm:ss #\u65E5\u671F\u683C\u5F0F
    time-zone: GMT+8 #\u4E1C\u516B\u533A
    #default-property-inclusion: non_null #\u503C\u4E3Anull\u7684\u5B57\u6BB5\u4E0D\u663E\u793A
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 50MB # \u6700\u5927\u652F\u6301\u6587\u4EF6\u5927\u5C0F
      max-request-size: 50MB # \u6700\u5927\u652F\u6301\u8BF7\u6C42\u5927\u5C0F
  thymeleaf: 
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  datasource: 
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:attendance
    username: wmt
    password: 
    schema: classpath:schema.sql
  jpa: 
    database: H2
    show-sql: true
    hibernate: 
      ddl-auto: update
  h2: 
    console: 
      enabled: true
      path: /h2
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis-config.xml
  